### ISSUE TITLE
Simplified Send/Recv API

### ISSUE THREAD

**Issue by seeyarh** [DouglasGray/xsk-rs#2]
Hey! Thanks for the awesome crate! I've been working on abstracting the queue management logic from the user in order to provide a simpler interface. The goal is to give the user of the library crossbeam senders/receivers for TX/RX. The user can then clone these senders/receivers in order to send and receive from multiple threads. You can take a look at that here
https://github.com/seeyarh/xsk-rs/blob/feature/send-recv-interface/tests/send_recv_tests.rs

Are you interested in these features? If so, I'll put out a PR once they are more complete. Otherwise, no worries, I'll keep working on my own fork.

**Comment by DouglasGray** [comment]
Hello! Sorry for the late reply, I didn't notice you'd opened an issue. I'll have to set notifications louder. I dig the idea, however I think it'd be better if we had some trait which defined a simplified API, and then this could be an implementation of that? I've been meaning to look into something for simplifying the API and doing the whole queue management for a while, so I'll try take a look at this soon and maybe we can converge on a helpful API.
