### ISSUE TITLE
Make file descriptor accessible

### ISSUE THREAD

**Issue by trinity-1686a** [DouglasGray/xsk-rs#4]
By default, libbpf loads a small xdp program redirecting all traffic to the af_xdp socket. However sometime one don't want all traffic to be redirected. While it's possible to ask this crate to not register libbpf default program (using `LibbpfFlags::XSK_LIBBPF_FLAGS__INHIBIT_PROG_LOAD`), it's then not possible to register the xsk fd, so the program one loads can't actually send packets to userspace.
Making [`Fd::id`](https://github.com/DouglasGray/xsk-rs/blob/4f1d39c24668458e45a6dede989869d7ee3dffa8/src/socket/fd.rs#L51) public would be enough to allow this use case (with a bit of documentation)

**Comment by DouglasGray** [comment]
Hi, apologies for the delay! Makes sense, I will take a look at your PR tomorrow. Thanks for submitting.
