### ISSUE TITLE
Ownership of `FrameDesc` and `Umem`

### ISSUE THREAD

**Issue by tdittr** [DouglasGray/xsk-rs#7]
Hi,

thanks for creating this nice library :)

One thing that is a bit hard to use for me is that `FrameDesc`s do not own the memory they point to in the `Umem`. For example if I want to write a packet to a Frame I have to have a `&mut Umem` even though there should always be just one `FrameDesc` be pointing at one part of the `Umem`.

I sometimes want to keep Frames around for a longer time (reassemble some streams, then check, and then retransmit or drop). So it would be nice if I could just store them in a `struct`, send them to another thread and then process them.

I have an idea to address this. A `struct Frame` that signifies ownership of part of the `Umem`. That can be passed by value to the queues (fill/tx) where they would be put on a list of kernel owned buffers. And when reading from the kernel (completion/rx) we can recreate a `Frame` to mark the user as owner. This would also make `produce` and `consume` safe as the ownership system makes sure only either the kernel or the user owns a buffer.

The `MmapArea` would then be an `Arc` to share the ownership between all the `Frame`s. And the `Frame`s could implement `Deref` and `DerefMut` to allow direct access to their part of the memory.

This would require some changes in the API though. I can put my ideas into a draft-PR if you are interested and think this could be a good idea.

**Comment by DouglasGray** [comment]
Hi, thank you for the feedback! It's taking some time but this is actually something I'm currently working on, indeed I also find the current API not so great. I've been a bit busy with work and such but will try move it along, and If you wish to throw some ideas into a draft PR that'd be great as well - it's always helpful seeing other implementations!

**Comment by tdittr** [comment]
Hi I tried out my idea in a draft PR: #8 

I started a bit too ambitious with the Frames struct so it became quite large already. Then I tried to integrate it in the existing structure. I skipped most of the tests and examples, but I can finish those if you like the interface.

I think the usage can best be seen in the `hello_xdp.rs'' example :)

I'm not sure if passing `VecDeque` is a good idea, but I wanted to have a way to handle if more frames are passed then have space in the ring-buffer.

What do you think?

**Comment by tdittr** [comment]
I tried the idea with returning a `Vec<Frame>` with the `Frame`s that did not fit in the Ringbuffer. It is quite nice as we can use `#[must_use]` on the functions to remind the user to handle those frames instead of dropping them.

**Comment by DouglasGray** [comment]
Hi, just writing to mention I'm closing this issue. I've released a new version which hopefully clears up your difficulties re concurrent access. Re making `produce` and `consume` safe, I feel it would be easier to do this with a wrapper struct that handles buffer management rather than within the `produce` and `consume` functions themselves, since it'd be good to try keep these as fast as possible and avoid allocations. Finally there is also an added example for using shared UMEM :)
